apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trivy-vex-app.fullname" . }}
  labels:
    {{- include "trivy-vex-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "trivy-vex-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trivy-vex-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "trivy-vex-app.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /debug/health
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /debug/health
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_ACCOUNT
              value: {{ include "trivy-vex-app.fullname" . }}
          volumeMounts:
            - name: ai-key
              mountPath: "/etc/config"
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ai-key
          secret:
            secretName: gemini-api-key
            optional: true
            items:
              - key: GEMINI_API_KEY
                path: gemini-api-key
